fix(types) i matched the models like the frontend
firstplug/First-Plug-Platform-Api pull request #44
Opened 2023-12-14 00:30 UTC by nahuelRo

2023-12-18 22:12 UTC, sebikap-gm2 requested changes

2023-12-18 22:12 UTC, sebikap-gm2 commented on api/types/order.ts
> +  "OrderConfirmed",
`Confirmed`

2023-12-18 22:12 UTC, sebikap-gm2 commented on api/services/member.ts
> +      throw new Error("the team member was not found");
```
const ERRORS = {
   MemberNotFound: 'The member is not registered',
} as const
type Error = keyof typeof ERRORS
type ErrorMessage = typeof ERRORS[Error]

throw new Error(ERRORS.MemberNotFound)
```

2023-12-18 22:12 UTC, sebikap-gm2 commented on api/models/Member.models.ts
> +export const MemberRepository = mongoose.model("TeamMember", MemberSchema);
TeamMember -> Member

2023-12-18 22:21 UTC, nahuelRo commented on api/services/member.ts
> +      throw new Error("the team member was not found");
TODO: on a different branch

2023-12-19 22:08 UTC, sebikap-gm2 approved these changes

2023-12-19 22:08 UTC, merged