feat(user credentials): register thirt party platform and credentials
firstplug/First-Plug-Platform-Api pull request #49
Opened 2023-12-31 20:26 UTC by nahuelRo

2024-01-03 21:29 UTC, sebikap-gm2 requested changes

2024-01-03 21:29 UTC, sebikap-gm2 commented on api/models/base.models.ts
> +      default: null,
Review:
Can we leave this as required, and manually specify which schema can support a null tenantId (such as UserSchema when User is first created)?

2024-01-03 21:29 UTC, sebikap-gm2 commented on api/routes/auth.routes.ts
> +authRoutes.post("/registerplatform", AuthController.registerPlatform);
registerAuthenticationProvider

2024-01-03 21:29 UTC, sebikap-gm2 commented on api/services/auth.services.ts
> +  static async validateIfExistEmail(email: User["email"]): Promise<void> {
Don't specify, let TS infer

2024-01-03 21:29 UTC, sebikap-gm2 commented on api/controllers/auth.controller.ts
> +      await AuthServices.validateIfExistEmail(email);
AuthController should handle "email already exists" logic

2024-01-03 21:29 UTC, sebikap-gm2 commented on api/types/user.ts
> +export type UserEntity = Document & User & BaseEntity;
Move on top of UserJWT

2024-01-03 21:29 UTC, sebikap-gm2 commented on api/types/user.ts
> +export type UserEntity = Document & User & BaseEntity;
BaseEntity already extends Document

2024-01-03 21:29 UTC, sebikap-gm2 commented on api/utils/bcryptFunctions.ts
> +): Promise<boolean> {
Let TS infer

2024-01-03 21:29 UTC, sebikap-gm2 commented on api/utils/bcryptFunctions.ts
> +    throw new Error(`Wrong password! Please try again`);
Non specific password error message

2024-01-07 18:14 UTC, nahuelRo commented on api/models/base.models.ts
> +      default: null,
I was looking to solve this problem with moongose ​​and I didn't find much information, what I did in the user shema is not to inherit from baseEntity but to have the same types as the other schemas that do inherit from baseEntity

2024-01-10 21:39 UTC, sebikap-gm2 approved these changes

2024-01-10 21:39 UTC, merged